chart_vars = {
    'pwat': {
        'var_name': 'Precipitable_water_entire_atmosphere_single_layer',
        'title': 'Precipitable Water',
        'position': 1,
        'dims': None,
        'cmap': 'YlGn',
        'alpha': 1,
        'units': 'mm',
        'second_var_name': None,
        'second_var_dims': None,
        'second_var_options': None,
    },
    'sbcape': {
        'var_name': 'Convective_available_potential_energy_surface',
        'title': 'SBCAPE',
        'position': 2,
        'dims': None,
        'cmap': 'RdPu',
        'alpha': 1,
        'units': 'J/kg',
        'second_var_name': None,
        'second_var_dims': None,
        'second_var_options': None,
    },
    'total_cloud': {
        'var_name': 'Total_cloud_cover_entire_atmosphere',
        'title': 'Total Cloud Cover',
        'position': 3,
        'dims': None,
        'cmap': 'gray',
        'alpha': 0.7,
        'units': 'Percent Coverage',
        'second_var_name': None,
        'second_var_dims': None,
        'second_var_options': None,
    },
    'wind_300': {
        'var_name': 'u-component_of_wind_isobaric',
        'title': '300hpa Winds',
        'position': 4,
        'dims': {'isobaric1': 10},
        'cmap': 'Blues',
        'alpha': 1,
        'units': 'm/s',
        'second_var_name': 'v-component_of_wind_isobaric',
        'second_var_dims': {'isobaric1': 10},
        'second_var_options': None,
    },
    'temp_500': {
        'var_name': 'Temperature_isobaric',
        'title': '500hpa Temperature',
        'position': 4,
        'dims': {'isobaric1': 11},
        'cmap': 'Reds',
        'alpha': 1,
        'units': 'K',
        'second_var_name': None,
        'second_var_dims': None,
        'second_var_options': None,
    }
}